define([], function() {
  return {
    "ResolvedQueryLabel": "Keywords sent as Querytext (resolved)",
    "SourceIdLabel": "Result source ID",
    "ExportColumnsLabel": "CSV columns (managed properties)",
    "ExportColumnsDescription": "Comma-separated names, e.g. Title,Path,Author,ModifiedOWSDATE,FileType. IndexDocId is added automatically for paging if omitted. Empty uses Title,Path,Author.",
    "CsvDateColumnsLabel": "Date columns (optional)",
    "CsvDateColumnsDescription": "Comma-separated managed property names used for two things: (1) format those columns as MM/dd/yyyy in the CSV, and (2) treat matching PnP refiner filterName values in the URL `f` JSON as date refiners (FQL range). You can also add a relative filter by writing `Field-50` or `Field+7` (UTC midnight) which adds an extra filter `Field >= today-50d` (ANDed with existing ranges). Examples: Created-50,LastModifiedTime-30,ModifiedOWSDATE-90,RefinableDate01-7. Built-in detection still applies when this is blank (RefinableDate*, created/last modified, *owsdate*, *datetime*).",
    "UseSearchUrlForFiltersLabel": "Use Search URL for filters and keywords",
    "SearchUrlLabel": "Search page URL",
    "SearchUrlDescription": "When \u201cUse Search URL for filters and keywords\u201d is on, paste a full or relative URL whose query string (and hash query, if used) contains the PnP parameters: k, q, f, f_<guid>, sourceid, etc. \u2014 typically copied from the browser address bar on your search results page. When the option is off, the current page URL is used. Relative URLs resolve against this site. The page search box is not used when Search URL is on.",
    "SearchUrlPropertyOriginLabel": "Search URL (property)",
    "ButtonAppearanceGroupLabel": "Export button appearance",
    "ExportButtonTextLabel": "Export button text",
    "ExportButtonTextDescription": "Leave blank to use the default label.",
    "CancelButtonTextLabel": "Cancel button text (debug mode)",
    "CancelButtonTextDescription": "Shown only when debug is on. Leave blank for the default.",
    "ExportButtonBackgroundLabel": "Button background color",
    "ExportButtonTextColorLabel": "Button text color",
    "ExportButtonBorderColorLabel": "Button border color",
    "ExportButtonBorderRadiusLabel": "Button corner radius",
    "ExportButtonFontSizeLabel": "Button font size",
    "ExportButtonWidthLabel": "Button width",
    "ExportButtonHeightLabel": "Button height",
    "ExportButtonColorFieldsDescription": "Optional. Hex only, e.g. #0078d4 or #fff. Invalid values are ignored.",
    "ExportButtonRadiusDescription": "Optional. Examples: 4px, 0, 2px.",
    "ExportButtonLengthFieldsDescription": "Optional. Use a length such as 14px, 120px, 32px, 1rem. Invalid values are ignored.",
    "DebugApiLabel": "Show debug details on the page",
    "WebPartTitle": "Search Export CSV",
    "WebPartDescription": "Exports SharePoint search results to CSV. Keywords: URL (e.g. k, q) or page search box; refiners: `f`.",
    "QuerySourceLabel": "Querytext source",
    "SourceIdSourceLabel": "SourceId source",
    "FromPropertyLabel": "Property pane",
    "FromUrlLabel": "URL parameter",
    "NotSetLabel": "Not set",
    "ExportButtonLabel": "Export CSV",
    "CancelButtonLabel": "Cancel",
    "SourceIdRequiredError": "Please configure the Result source ID.",
    "InvalidSourceIdGuidError": "Result source ID must be a single GUID (8-4-4-4-12 hex), not a name or URL. Copy the ID from PnP \u2192 Data sources \u2192 Result source id.",
    "ExportStarted": "Export started...",
    "ExportInProgress": "Exporting",
    "PageLabel": "page",
    "ExportCancelled": "Export cancelled.",
    "CancellingMessage": "Cancelling...",
    "ExportCappedMessage": "Export stopped at safety cap",
    "ExportCompleted": "Export complete. Rows exported:",
    "ExportFailedPrefix": "Export failed:",
    "FiltersFromUrlLabel": "Refiners for export (URL `f`, other params, or page UI)",
    "NoFiltersInUrlLabel": "None in URL",
    "FiltersParseFailedLabel": "Could not parse `f` parameter",
    "FiltersDiscoveredInUrlLabel": "URL (any param)",
    "FiltersFromUiLabel": "Page filters (no `f` in URL – inferred from visible File Type control)",
    "EffectiveFilterKqlLabel": "Effective extra KQL / FQL (export)",
    "SearchQueryFromPageSearchBoxLabel": "Page search box (text input)",
    "ExportNoKeywordsWithRefinersHint": "The `f` parameter holds refiners only. There is no keyword in the URL and none from the page search box, so export uses * plus those refiners. Enable PnP \u2192 update page URL with the search query so `k` matches Search Results.",
    "ExportNoKeywordsNoRefinersHint": "No search keywords in URL / search box and no refiners \u2014 export uses * only.",
  }
});
