define([], function() {
  return {
    "ResolvedQueryLabel": "Keywords sent as Querytext (resolved)",
    "SourceIdLabel": "Result source ID",
    "ExportColumnsLabel": "CSV columns (managed properties)",
    "ExportColumnsDescription": "Comma-separated names, e.g. Title,Path,Author,ModifiedOWSDATE,FileType. IndexDocId is added automatically for paging if omitted. Empty uses Title,Path,Author.",
    "DebugApiLabel": "Show debug details on the page",
    "WebPartTitle": "Search Export CSV",
    "WebPartDescription": "Exports SharePoint search results to CSV. Keywords: URL (e.g. k, q) or page search box; refiners: `f`.",
    "QuerySourceLabel": "Querytext source",
    "SourceIdSourceLabel": "SourceId source",
    "FromPropertyLabel": "Property pane",
    "FromUrlLabel": "URL parameter",
    "NotSetLabel": "Not set",
    "ExportButtonLabel": "Export CSV",
    "CancelButtonLabel": "Cancel",
    "SourceIdRequiredError": "Please configure the Result source ID.",
    "InvalidSourceIdGuidError": "Result source ID must be a single GUID (8-4-4-4-12 hex), not a name or URL. Copy the ID from PnP \u2192 Data sources \u2192 Result source id.",
    "ExportStarted": "Export started...",
    "ExportInProgress": "Exporting",
    "PageLabel": "page",
    "ExportCancelled": "Export cancelled.",
    "CancellingMessage": "Cancelling...",
    "ExportCappedMessage": "Export stopped at safety cap",
    "ExportCompleted": "Export complete. Rows exported:",
    "ExportFailedPrefix": "Export failed:",
    "FiltersFromUrlLabel": "Refiners for export (URL `f`, other params, or page UI)",
    "NoFiltersInUrlLabel": "None in URL",
    "FiltersParseFailedLabel": "Could not parse `f` parameter",
    "FiltersDiscoveredInUrlLabel": "URL (any param)",
    "FiltersFromUiLabel": "Page filters (no `f` in URL – inferred from visible File Type control)",
    "EffectiveFilterKqlLabel": "Effective extra KQL / FQL (export)",
    "SearchQueryFromPageSearchBoxLabel": "Page search box (text input)",
    "ExportNoKeywordsWithRefinersHint": "The `f` parameter holds refiners only. There is no keyword in the URL and none from the page search box, so export uses * plus those refiners. Enable PnP \u2192 update page URL with the search query so `k` matches Search Results.",
    "ExportNoKeywordsNoRefinersHint": "No search keywords in URL / search box and no refiners \u2014 export uses * only.",
  }
});
